# =========================
# Dockerfile Streamlit - RUCHE
# =========================

FROM python:3.12

# Empêche Python de créer des fichiers .pyc
ENV PYTHONDONTWRITEBYTECODE=1

# Logs Python flush immédiat
ENV PYTHONUNBUFFERED=1

# Dossier de travail
WORKDIR /app

# -------------------------------------------------
# Dépendances système minimales
# -------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------
# Dépendances Python
# -------------------------------------------------
RUN pip install --no-cache-dir \
    torch==2.2.2+cpu \
    --extra-index-url https://download.pytorch.org/whl/cpu
COPY requirements_streamlit.txt .
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements_streamlit.txt

    # -------------------------------------------------
# Copie du code Streamlit + lib commune
# -------------------------------------------------
COPY streamlit/ streamlit/
COPY ruche/ ruche/
COPY documentation/ documentation/
COPY etl/ etl/

# -------------------------------------------------
# Exposition du port Streamlit
# -------------------------------------------------
EXPOSE 8501

# -------------------------------------------------
# Lancement de l'application
# -------------------------------------------------
CMD ["streamlit", "run", "streamlit/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
